### ISSUE TITLE
Refactor users/groups rights

### ISSUE THREAD

**Issue by shprink** [OpenBankingToolkit/openbanking-directory#103]
- [ ] Make sense out of the existing groups `https://github.com/OpenBankingToolkit/openbanking-directory/issues/99`
- [ ] Reorganise groups (add, remove, simplify)
- [ ] Add a real admin group (with all access if that makes sense)
- [ ] Reflects new admin rights in the UI

**Comment by jorgesanchezperez** [comment]
Closed to be old.
